version: '3.8'
services:
  halalina-ml:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app/__main__.py
    networks:
      - halalina-network

networks:
  halalina-network:
    driver: bridge
