name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with unittest
        run: python -m unittest discover -s

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/halalina-ml:staging .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/halalina-ml:staging

  deploy:
    name: Pull and Run on VPS (Staging)
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop and Remove Old Container
        run: |
          docker stop halalina-ml-staging || true
          docker rm halalina-ml-staging || true

      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/halalina-ml:staging

      - name: Run New Container
        run: |
          docker run -d \
            --name halalina-ml-staging \
            --env-file ~/halalina-ml/.env.staging \
            --network halalina-staging-network \
            -p 5502:5001 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/halalina-ml:staging
